version: '3'

services:
    web:
        build: docker/web/
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        environment:
            - DOTNET_USE_POLLING_FILE_WATCHER=1

    devtools:
        build: docker/devtools/
        volumes:
            - .:/app
        depends_on:
            - web
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            # management UI:
            - 15672:15672